### ISSUE TITLE
Facebook integration breaks build while logging in

### ISSUE THREAD

**Issue by ParasDPain** [concierge/Kassy#166]
Can you confirm whether this is a local cause or an upstream issue?

Here's the `debug log`

```
info Logging in... 
info Logged in 
info Request to reconnect 
info Request to pull 1 
info Request to pull 2 
info Request to thread_sync 
info Done logging in. 
ERR! Error in login: TypeError: Cannot read property 'sendImage' of undefined
ERR! Error in login:     at facebook.js:98:23
ERR! Error in login:     at /root/Dev/Kassy_3.5.1/node_modules/facebook-chat-api/index.js:406:14
ERR! Error in login:     at tryCatcher (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in login:     at Promise._settlePromiseFromHandler (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Error in login:     at Promise._settlePromiseAt (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Error in login:     at Async._drainQueue (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/async.js:128:12)
ERR! Error in login:     at Async._drainQueues (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in login:     at Immediate.Async.drainQueues [as _onImmediate] (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in login:     at tryOnImmediate (timers.js:534:15)
ERR! Error in login:     at processImmediate [as _immediateCallback] (timers.js:514:5)
ERR! Error in login:  [TypeError: Cannot read property 'sendImage' of undefined]
undefined
```

**Comment by mrkno** [comment]
Probably something caused by enabling strict mode the other day. Try now after this push https://github.com/concierge/Kassy/commit/9701af39e1f71c9786f267218b00f0a9f9bbadd6

**Comment by ParasDPain** [comment]
It runs fine now :+1: Cheers!

**Comment by ParasDPain** [comment]
Noticed this after sending the first command from a group chat (Possibly unrelated to this issue, regardless)
It didn't happen on subsequent commands though

```
ERR! Error in getUserInfo TypeError: Cannot set property '100011383530804' of undefined
ERR! Error in getUserInfo     at callback (facebook.js:17:13)
ERR! Error in getUserInfo     at /root/Dev/Kassy_3.5.1/node_modules/facebook-chat-api/src/getUserInfo.js:49:14
ERR! Error in getUserInfo     at tryCatcher (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/util.js:26:23)
ERR! Error in getUserInfo     at Promise._settlePromiseFromHandler (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/promise.js:507:31)
ERR! Error in getUserInfo     at Promise._settlePromiseAt (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/promise.js:581:18)
ERR! Error in getUserInfo     at Async._drainQueue (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/async.js:128:12)
ERR! Error in getUserInfo     at Async._drainQueues (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/async.js:133:10)
ERR! Error in getUserInfo     at Immediate.Async.drainQueues [as _onImmediate] (/root/Dev/Kassy_3.5.1/node_modules/bluebird/js/main/async.js:15:14)
ERR! Error in getUserInfo     at tryOnImmediate (timers.js:534:15)
ERR! Error in getUserInfo     at processImmediate [as _immediateCallback] (timers.js:514:5)
ERR! Error in getUserInfo  [TypeError: Cannot set property '100011383530804' of undefined]
```

**Comment by mrkno** [comment]
hmmmm.... I tried to replicated and got a different exception (clearly in the same place though):
```
ERR! Error in getThreadInfo TypeError: Cannot read property 'name' of undefined
ERR! Error in getThreadInfo     at C:\Users\Matthew\Desktop\Kassy\node_modules\facebook-chat-api\src\getThreadInfo.js:36:46
ERR! Error in getThreadInfo     at tryCatcher (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\util.js:26:23)
ERR! Error in getThreadInfo     at Promise._settlePromiseFromHandler (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\promise.js:507:31)
ERR! Error in getThreadInfo     at Promise._settlePromiseAt (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\promise.js:581:18)
ERR! Error in getThreadInfo     at Async._drainQueue (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\async.js:128:12)
ERR! Error in getThreadInfo     at Async._drainQueues (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\async.js:133:10)
ERR! Error in getThreadInfo     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\async.js:15:14)
ERR! Error in getThreadInfo     at tryOnImmediate (timers.js:543:15)
ERR! Error in getThreadInfo     at processImmediate [as _immediateCallback] (timers.js:523:5)
ERR! Error in getThreadInfo  TypeError: Cannot read property 'name' of undefined
ERR! Error in getThreadInfo     at C:\Users\Matthew\Desktop\Kassy\node_modules\facebook-chat-api\src\getThreadInfo.js:36:46
ERR! Error in getThreadInfo     at tryCatcher (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\util.js:26:23)
ERR! Error in getThreadInfo     at Promise._settlePromiseFromHandler (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\promise.js:507:31)
ERR! Error in getThreadInfo     at Promise._settlePromiseAt (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\promise.js:581:18)
ERR! Error in getThreadInfo     at Async._drainQueue (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\async.js:128:12)
ERR! Error in getThreadInfo     at Async._drainQueues (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\async.js:133:10)
ERR! Error in getThreadInfo     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Matthew\Desktop\Kassy\node_modules\bluebird\js\main\async.js:15:14)
ERR! Error in getThreadInfo     at tryOnImmediate (timers.js:543:15)
ERR! Error in getThreadInfo     at processImmediate [as _immediateCallback] (timers.js:523:5)
```

Other interesting features:
- The code this is happening in is where we associate names to ID's.
- Kassy does not crash
- Subsequent messages (even ones which involve name lookup) work as intended

Given this used to work without problem I'm guessing it is upstream but I cannot be sure (particularly given babel has made the line numbers on exceptions useless).

**Comment by mrkno** [comment]
Ok, the second problem is being caused by the line:
`name: threadData.name || userData.name,`
In the current release version of facebook-chat-api. This [has already been fixed upstream](https://github.com/Schmavery/facebook-chat-api/blob/master/src/getThreadInfo.js#L36).

As it doesn't actually cause Kassy to crash (in my case) or perform any invalid behavior except on the first message, I suggest it is just ignored until the next release.

Feel free to re-open if it does cause a longer term problem.
