### ISSUE TITLE
Loading module 'config.json'...  

### ISSUE THREAD

**Issue by phillipadsmith** [concierge/Kassy#182]
I've upgraded Kassy to 3.5.1 and I'm getting this odd warning on startup:

```
Loading module 'config.json'...
TypeError: Instance is not a function
    at new Robot (robot.js:25:25)
    at Object.exports.loadModule (hubotModule.js:112:16)
    at Object.exports.loadModule (modules.js:35:45)
    at Platform.start (platform.js:111:37)
    at Object.exports.run (startup.js:28:18)
    at Object.<anonymous> (/Users/phillipadsmith/Development/kassy-dev/main.js:77:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:142:18)
    at node.js:939:3
Loading Failed
Could not load module 'config.json'. Does it have a syntax error?
Module "config.json" could not be loaded.
```

What's up with that @mrkno ?

**Comment by phillipadsmith** [comment]
Hmmm... never mind. After I rebased my fork the error went away.

**Comment by mrkno** [comment]
The source of this issue in case you encounter it again is that modules got moved to their own repos but the config and kassy.json files remained (it does a best effort when it can't find what it needs).

**Comment by phillipadsmith** [comment]
> The source of this issue in case you encounter it again is that modules got moved to their own repos

Okay, so now they're best loaded via KPM, or...?

**Comment by mrkno** [comment]
Just keep doing what you were doing before, it was a once off change that once resolved shouldn't affect you again.
